create table students(
student_id int generated always as identity,
first_name varchar(15) not null,
last_name varchar(15) not null,
email varchar(30) not null,
date_of_birth date,
primary key(student_id)
);

create table instructors (
  instructor_id INT generated always as identity (
start with 1000 increment by 100),
  first_name VARCHAR(15) not null,
  last_name VARCHAR(15) not null,
  email VARCHAR(30) not null,
  primary key(instructor_id)
);

create table courses (
  course_id INT generated by default as identity (
start with 100 increment by 10),
  instructor_id INT,
  course_name VARCHAR(60) not null,
  course_description TEXT,
  primary key(course_id),
  constraint fk_instructors
    foreign key(instructor_id)
    references instructors(instructor_id)
);


create table enrollments(
enrollment_id int generated always as identity(start with 500 increment by 50),
student_id int,
course_id int,
enrollment_date date,
grade char(1),
primary key(enrollment_id),
constraint fk_student foreign key(student_id) references students(student_id),
constraint fk_course foreign key(course_id) references courses(course_id)
);

